### ISSUE TITLE
Tried to update all dependcies to latest, and lein test failed...

### ISSUE THREAD

**Issue by dcj** [DaveWM/willa#19]
Not sure if this is supposed to work, but FYI:

`Syntax error (ClassNotFoundException) compiling new at (jackdaw/test.clj:250:5).
org.apache.kafka.streams.processor.internals.ChangelogRegister`

and the second time I run lein test I get:

`Syntax error (ClassNotFoundException) compiling new at (jackdaw/test.clj:250:5).
org.apache.kafka.streams.processor.internals.ClientUtils$QuietStreamsConfig`

Here is the project.clj I tried to use:

```
(defproject willa "0.2.0"
  :description "A Clojure DSL for Kafka Streams"
  :url "https://github.com/DaveWM/willa"
  :license {:name "GPL V3"
            :url "https://www.gnu.org/licenses/gpl-3.0.en.html"}
  :dependencies [[org.clojure/clojure "1.10.3"]
                 [fundingcircle/jackdaw "0.7.8"]
                 [aysylu/loom "1.0.2"]
                 [rhizome "0.2.9"]
                 [org.clojure/math.combinatorics "0.1.6"]]
  :repl-options {:init-ns willa.core}
  :repositories [["confluent" "https://packages.confluent.io/maven/"]
                 ["clojars" "https://clojars.org/repo/"]]
  :profiles {:test {:dependencies [[org.apache.kafka/kafka-streams-test-utils "2.7.0"]
                                   [log4j/log4j "1.2.17"]]}
             :dev {:dependencies [[org.clojure/test.check "1.1.0"]]}
             :ci {:jvm-opts ["-Djava.awt.headless=true"]}})
```

I rarely use lein test, so maybe I don't know what I am doing....

Then I went back to your master branch, and that branch tests fine (as one would expect):

```
lein test willa.test-utils
lein test willa.unit.core-test
lein test willa.unit.experiment-and-ttd-congruity-test
lein test willa.unit.streams-test
lein test willa.unit.utils-test

Ran 19 tests containing 43 assertions.
0 failures, 0 errors.
```

**Comment by dcj** [comment]
Also, Clojars reports version 0.2.1, but the project.clj shows 0.2.0....

**Comment by DaveWM** [comment]
Hey @dcj, thanks for raising this issue. The version in `project.clj` should be correct now. 

I've tried updating the dependency versions, and I also get that error. I think the issue is with the `kafka-streams-test-utils` dep, it seems that Jackdaw expects version `2.3.1` (see [here](https://github.com/FundingCircle/jackdaw/blob/b4f67106cc12a78d9dcc64b6cba668ab6a804d04/project.clj#L23)), and doesn't seem to work with version `2.7.0`. If that's a problem for you, I'd raise an issue on the Jackdaw repo about it, or ask in the Jackdaw channel on the clojurians slack. I've updated the other dependency versions in `master`.
