### ISSUE TITLE
Access state store in xform

### ISSUE THREAD

**Issue by CurriedFloat** [DaveWM/willa#20]
I'm trying to figure out if it is possible to access a local state store inside
a willa workflow.

Is their something like transform from jackdaw?
https://cljdoc.org/d/fundingcircle/jackdaw/0.8.0/api/jackdaw.streams#transform

For context I'm trying to do something like:
https://github.com/brycecovert/clojure-event-sourcing/blob/8dd6974eb050c41bf8f5600bc2ed9e213ff2f71e/src/event_sourcing/passenger_counting.clj#L64

**Comment by DaveWM** [comment]
There's nothing like that built in to Willa unfortunately, it tries to abstract away interactions with state stores. However,you should be able to achieve the same result by joining to the `passengers-ktable` instead of  querying its state store. If that doesn't work, you can also use the [build-topology-unsafe!](https://github.com/DaveWM/willa/blob/5ef0f18485b8a733304306a03cd8fc5f665e565f/src/willa/core.clj#L135) function (instead of `build-topology!`) to override how Willa builds your `KStream`, and use the `transform-with-stores` function in the override.

**Comment by CurriedFloat** [comment]
I started out by trying to join approach and for some reason (that I cant remember) I
couldn't get it to work so I figured I had to query the state store.

I will try the join approach again, and fall back to the override or ask a follow-up question on joining later.

Thanks :)
